# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoPub Mediation Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoPub Mediation Demo
  pod 'MoPub-HyBid-Adapters', '2.4.8.1'
end
